export { createEmptyExamDocument } from './factory';
export {
  migrateExamDocument,
  ExamDocumentMigrationError,
  UnsupportedExamDocumentVersionError,
} from './migrations';
export {
  CURRENT_SCHEMA_VERSION,
  PHASE1_SCHEMA_VERSION,
  PHASE2_SCHEMA_VERSION,
  PHASE3_SCHEMA_VERSION,
  PHASE4_SCHEMA_VERSION,
  PHASE5_SCHEMA_VERSION,
  PHASE6_SCHEMA_VERSION,
  PHASE7_SCHEMA_VERSION,
  PHASE8_SCHEMA_VERSION,
  PHASE9_SCHEMA_VERSION,
  PHASE10_SCHEMA_VERSION,
  PHASE11_SCHEMA_VERSION,
  PHASE12_SCHEMA_VERSION,
  examDocumentSchema,
  parseExamDocument,
  safeParseExamDocument,
  type ExamDocument,
  type ExamMetadata,
} from './schema';
export {
  informationSeparatorModes,
  informationSpacingPresets,
  warningSpacingPresets,
  matchSpacingPreset,
  normalizeFrontMatterSpacing,
  normalizeInformationSeparator,
  validateInformationSeparatorText,
  validateLatexSkip,
  type FrontMatterSpacingPresetId,
} from './front-matter-options';
export {
  deserializeExamDocument,
  normalizeExamDocument,
  serializeExamDocument,
} from './serialization';
export { buildEffectiveFillinOptions } from './fillin-options';
export {
  buildPageFooterContent,
  compileFooterTemplate,
  DEFAULT_PAGE_FOOTER_TEMPLATE,
  PAGE_OPTION_KEYS,
  validateFooterTemplate,
  type FooterTemplateValidationResult,
} from './page-options';
export {
  formatJudgementAnswer,
  resolveJudgementSetup,
  type ResolvedJudgementSetup,
} from './judgement';
export {
  addInformationField,
  addQuestion,
  addNotice,
  addSection,
  addSubQuestionToProblem,
  appendBlankRefToStem,
  calculateDocumentStats,
  calculateSectionStats,
  formatSectionSummary,
  calculateTotalPointsMismatch,
  calculateScoreMarksEffectivePoints,
  commitChoiceLabelDraft,
  commitNoticeDraft,
  commitNumberDraft,
  createBlankSlot,
  createChoiceOption,
  createDefaultQuestion,
  createDefaultSection,
  createInformationField,
  createNoticeBlock,
  createScoreMark,
  createSubQuestion,
  duplicateChoiceOptionWithResult,
  duplicateQuestion,
  duplicateQuestionWithResult,
  duplicateSection,
  duplicateSubQuestionWithResult,
  getChoiceDisplayLabel,
  getScoreItemLabel,
  getScoreModeLabel,
  insertSectionAt,
  maxScoreMarkPoints,
  moveChoiceOption,
  moveInformationField,
  moveNotice,
  moveQuestion,
  moveSection,
  moveSubQuestion,
  nextChoiceLabel,
  removeBlankFromQuestion,
  removeChoiceOption,
  removeNotice,
  removeInformationField,
  replaceInformationField,
  replaceNotice,
  reviewQuestionScoreMarks,
  removeQuestion,
  resolveQuestionSelectionAfterDelete,
  removeSection,
  removeSubQuestion,
  setBlankAnswer,
  sumScoreMarks,
  updateQuestion,
  updateSection,
  updateSubQuestion,
  type AddSubQuestionResult,
  type ChoiceLabelDraftCommitResult,
  type DuplicateQuestionResult,
  type DuplicateChoiceOptionResult,
  type DuplicateSubQuestionResult,
  type ScoreReviewDiagnostic,
  type ScoreReviewDiagnosticCode,
  type CreateId,
  type NumberDraftCommitMode,
  type NumberDraftCommitResult,
} from './editor';
export {
  hasUnclosedInlineMath,
  parseRichContentInput,
  removeChoiceParenRefs,
  removeJudgementRefs,
  stringifyRichContentBlocks,
  type RichContentInputContext,
  type ParseRichContentOptions,
  type ParseRichContentResult,
  type RichContentParseDiagnostic,
  type RichContentParseDiagnosticCode,
  type TeacherContentStringifyContext,
} from './rich-content';
export {
  appendAnnotationReference,
  appendScoreReference,
  buildReferenceContextSummary,
  collectAnnotationReferenceIds,
  collectScoreReferenceIds,
  findTeacherReferenceTextRange,
  insertTeacherReferenceAtSelection,
  isScoreLevelOrderDescending,
  moveScoreMarkToSummary,
  parseInlineRichText,
  parseTeacherSolutionInput,
  reconcileTeacherSolutionBlocks,
  removeAnnotationReferences,
  removeScoreReferences,
  sortScoreLevelsDescending,
  stringifyInlineRichText,
  type ParseTeacherSolutionInput,
  type ParseTeacherSolutionResult,
  type InsertTeacherReferenceAtSelectionInput,
  type InsertTeacherReferenceAtSelectionResult,
  type TeacherReference,
  type TeacherContentConversionSummary,
  type TeacherContentDiagnostic,
  type TeacherContentDiagnosticCode,
} from './teacher-content';
export {
  DEFAULT_QUESTION_LABEL,
  formatQuestionLabel,
  getQuestionLabelPreset,
  getQuestionLabelPresetValue,
  getSectionNumberingMode,
  getSectionQuestionLabel,
  getSectionStartIndex,
  questionLabelPresets,
  resolveQuestionNumbers,
  type QuestionLabelPresetId,
  type QuestionLabelPresetSelection,
  type ResolvedQuestionNumber,
  type SectionNumberingMode,
} from './question-numbering';
export {
  createExamDocumentFromTemplate,
  examDocumentTemplates,
  type ExamDocumentTemplate,
  type ExamDocumentTemplateCategory,
  type ExamDocumentTemplateId,
} from './templates';
export type {
  Asset,
  BlankSlot,
  ChoiceOption,
  ChoicesSetup,
  ExamQuestion,
  ExamSection,
  ExamSetup,
  PageSetup,
  ExamZhDocumentOptions,
  ExamZhOptionBag,
  ExamZhOptionValue,
  InlineContent,
  InlineRichText,
  InlineRichTextContent,
  JudgementQuestionSetup,
  JudgementSetup,
  NumberingSetup,
  RichContentBlock,
  ScoreMark,
  ScoreMode,
  SolutionAnnotation,
  SubQuestion,
  SubQuestionGroup,
} from './model';
